
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXCLEM = 46;
  public static final int DOUBLEDOT = 38;
  public static final int BOOL = 8;
  public static final int CLOSEDPRANTHES = 32;
  public static final int CONST = 19;
  public static final int MM = 47;
  public static final int BOOL_CONST = 67;
  public static final int SEMI = 3;
  public static final int SIZEOF = 27;
  public static final int SMALLEQUAL = 59;
  public static final int COMMA = 20;
  public static final int CAROT = 55;
  public static final int DOUBLE = 12;
  public static final int STRING_CONST = 68;
  public static final int CLOSEDBRAK = 6;
  public static final int PLUSEQUAL = 82;
  public static final int FALSE = 75;
  public static final int PLUSASSIGN = 87;
  public static final int OPENCURLBRAK = 33;
  public static final int TILDA = 49;
  public static final int ADDRESS = 72;
  public static final int FLOAT = 9;
  public static final int GOTO = 76;
  public static final int CLOSEDCURLBRAK = 34;
  public static final int RECORD = 16;
  public static final int BIGEQUAL = 58;
  public static final int MOD = 52;
  public static final int REAL_CONST = 65;
  public static final int TRUE = 81;
  public static final int LONG = 10;
  public static final int PLUS = 45;
  public static final int DIVIDE = 51;
  public static final int EQUAL = 21;
  public static final int CHAR = 11;
  public static final int MULTASSIGN = 90;
  public static final int INPUT = 77;
  public static final int SWITCH = 30;
  public static final int FOR = 39;
  public static final int VOID = 14;
  public static final int EXTERN = 4;
  public static final int RETURN = 24;
  public static final int MULT = 50;
  public static final int NOTC = 64;
  public static final int INT_CONST = 37;
  public static final int MINUSEQUAL = 83;
  public static final int ELSE = 29;
  public static final int BREAK = 25;
  public static final int PP = 48;
  public static final int DOT = 86;
  public static final int BIGGER = 61;
  public static final int INT = 7;
  public static final int FUNCTIONSIGNATURE = 74;
  public static final int DIVIDEASSIGN = 89;
  public static final int EOF = 0;
  public static final int DEFAULT = 70;
  public static final int FUNCTION = 78;
  public static final int REPEAT = 40;
  public static final int UNITL = 41;
  public static final int MINUS = 44;
  public static final int OUTPUT = 79;
  public static final int IN = 43;
  public static final int OR = 53;
  public static final int error = 1;
  public static final int CHAR_CONST = 66;
  public static final int CONTINUE = 26;
  public static final int IF = 28;
  public static final int ID = 2;
  public static final int OF = 35;
  public static final int END = 18;
  public static final int MULTEQUAL = 84;
  public static final int OPENBRAK = 5;
  public static final int FOREACH = 42;
  public static final int EQEQUAL = 56;
  public static final int LONG_CONST = 69;
  public static final int ORC = 63;
  public static final int ANDC = 62;
  public static final int NOTEQUAL = 57;
  public static final int BEINGQ = 22;
  public static final int MINUSASSIGN = 88;
  public static final int BEGIN = 17;
  public static final int CASE = 36;
  public static final int ENDQ = 23;
  public static final int STRING = 13;
  public static final int SMALLER = 60;
  public static final int AND = 54;
  public static final int STATIC = 80;
  public static final int UMINUS = 71;
  public static final int DIVIDEEQUAL = 85;
  public static final int TYPESOFBYTECODE = 73;
  public static final int AUTO = 15;
  public static final int OPENPRANTHES = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "SEMI",
  "EXTERN",
  "OPENBRAK",
  "CLOSEDBRAK",
  "INT",
  "BOOL",
  "FLOAT",
  "LONG",
  "CHAR",
  "DOUBLE",
  "STRING",
  "VOID",
  "AUTO",
  "RECORD",
  "BEGIN",
  "END",
  "CONST",
  "COMMA",
  "EQUAL",
  "BEINGQ",
  "ENDQ",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "SIZEOF",
  "IF",
  "ELSE",
  "SWITCH",
  "OPENPRANTHES",
  "CLOSEDPRANTHES",
  "OPENCURLBRAK",
  "CLOSEDCURLBRAK",
  "OF",
  "CASE",
  "INT_CONST",
  "DOUBLEDOT",
  "FOR",
  "REPEAT",
  "UNITL",
  "FOREACH",
  "IN",
  "MINUS",
  "PLUS",
  "EXCLEM",
  "MM",
  "PP",
  "TILDA",
  "MULT",
  "DIVIDE",
  "MOD",
  "OR",
  "AND",
  "CAROT",
  "EQEQUAL",
  "NOTEQUAL",
  "BIGEQUAL",
  "SMALLEQUAL",
  "SMALLER",
  "BIGGER",
  "ANDC",
  "ORC",
  "NOTC",
  "REAL_CONST",
  "CHAR_CONST",
  "BOOL_CONST",
  "STRING_CONST",
  "LONG_CONST",
  "DEFAULT",
  "UMINUS",
  "ADDRESS",
  "TYPESOFBYTECODE",
  "FUNCTIONSIGNATURE",
  "FALSE",
  "GOTO",
  "INPUT",
  "FUNCTION",
  "OUTPUT",
  "STATIC",
  "TRUE",
  "PLUSEQUAL",
  "MINUSEQUAL",
  "MULTEQUAL",
  "DIVIDEEQUAL",
  "DOT",
  "PLUSASSIGN",
  "MINUSASSIGN",
  "DIVIDEASSIGN",
  "MULTASSIGN"
  };
}

